name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Added'
    labels:
      - 'feature'
  - title: 'Changed'
    labels:
      - 'enhancement'
      - 'dependency-update'
  - title: 'Fixed'
    labels:
      - 'fix'
      - 'bug'
exclude-labels:
  - 'skip-changelog'
  - 'docs'
  - 'build'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes
  $CHANGES